### ISSUE TITLE
BUG: Download broken when generating multiple gifs without refresh

### ISSUE THREAD

**Issue by clairelines** [PatMattei/messagesfromwill#2]
when you generate a gif and then immediately generate a different gif, the download button appears three times and fails to download.

**Comment by clairelines** [comment]
![bug](https://cloud.githubusercontent.com/assets/5098413/18181507/69f28044-7059-11e6-8181-c66a05d37e74.gif)

**Comment by PatMattei** [comment]
That should be fixed, let me know if not
